### ISSUE TITLE
Exception in new InputStreamReader

### ISSUE THREAD

**Issue by aloorir** [patriques82/alphavantage4j#15]
I appreciate your help, I am getting  an exception in following line: 

I believe the error is in  Class : AlphaVantageConnector.java, line 43.

InputStreamReader inputStream = new InputStreamReader(connection.getInputStream(),"UTF-8");

could you please give me some directions or guide to work with. I know basics but not an expert in java.
Exception : Something went wrong

Thank you for your support!

**Comment by patriques82** [comment]
Can you please provide the use case with some code, so the problem can be recreated.

**Comment by aloorir** [comment]
Sure, only things i changed from the original code are 
1) url from "https" to "http" in AlphaVantageConnector.java 
2) changed apikey to my personal key and   increased timeout to 9000 in App.java[Usage].

then ran app.java which is usage from readme.md imported all the required classes and packages. compiled fine and got following exception :

Exception in thread "main" java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at co.alphavantage.output.JsonParser.parseJson(JsonParser.java:51)
	at co.alphavantage.output.timeseries.IntraDay.from(IntraDay.java:32)
	at co.alphavantage.TimeSeries.intraDay(TimeSeries.java:39)
	at App.main(App.java:21)

Just wanted to know if i am doing anything wrong. or need to include anything?

**Comment by aloorir** [comment]
I fixed it thanks-

**Comment by patriques82** [comment]
Just of curiosity, what was the problem?
