### ISSUE TITLE
Maven:  Jar file not downloaded.

### ISSUE THREAD

**Issue by deragon** [patriques82/alphavantage4j#20]
Using Maven 3.5.2 (latest version, tried 3.3.9 also), the jar file for the artefact simply does not get downloaded.

I am using a settings.xml that is a described on the README.MD file as is (not merged with any other settings).  I deleted my "${HOME}/.m2/repository" directory and all artifacts used by my project where downloaded again, except for alphavintage4j.

There are no errors reported by Maven.  It is not clear if the problem is with Maven, my personal settings or alphavantage4j's repository.  But since all other artifacts jars are downloaded and I successfully built other projects not using alphavantage4j's artifact, it seams that the problem lies with alphavantage4j's repository.

**Comment by Gregam3** [comment]
I am also having this issue, I attempted to use version 1.1 and it is not available.

**Comment by karumo** [comment]
I got the jar using this link here ...
https://dl.bintray.com/patriques82/maven/org/patriques/alphavantage4j/1.1/

**Comment by deragon** [comment]
@patriques82, thank you for fixing the issue and for your time on this project; it is appreciated.

**Comment by sreenathchakkingal** [comment]
I see the jar in https://dl.bintray.com/patriques82/maven/org/patriques/alphavantage4j/1.1/. But how do i reference that in my maven ?
This is my maven entry and it does not work. 
<dependency>
			<groupId>org.patriques</groupId>
			<artifactId>alphavantage4j</artifactId>
			<version>1.4</version> 
		</dependency>

**Comment by gmartinezgil** [comment]
Inside your pom.xml file you need to declare the following on the repositories section:

```
<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>bintray-patriques82-maven</id>
			<name>bintray</name>
			<url>https://dl.bintray.com/patriques82/maven</url>
		</repository>
	</repositories>
```

And then reference the dependency like this:

```
<dependency>
      <groupId>org.patriques</groupId>
      <artifactId>alphavantage4j</artifactId>
      <version>1.4</version>
</dependency>

```
Hope it helps you.
