### ISSUE TITLE
Build.Gradle Issue

### ISSUE THREAD

**Issue by JZhou86** [patriques82/alphavantage4j#21]
We are a student group working on a class project to create a stock market game Android app. We are hitting this error: 
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'. > com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/Rahul/.gradle/caches/modules-2/files-2.1/org.patriques/alphavantage4j/1.1/1ba9b0b20b63704021cc32efccfb26a67b5dcd83/alphavantage4j-1.1.jar

due to us trying to add this to our build.gradle:
compile 'org.patriques:alphavantage4j:1.1'

We have tried copying the proposed lines of code into our build.gradle file as well as importing the jar files. We were wondering if you would know why this issue was occurring. Thanks!

**Comment by patriques82** [comment]
I actually can´t figure out what went wrong there. I have very little experience with the android environment so I can´t follow the stacktrace. 

Searching on stackoverflow I found a solution that says you can do this in Android Studio to fix the problem.
File > Invalidate Caches / Restart.. > Invalidate & Restart

Please tell me and others how you reached a solution.
