### ISSUE TITLE
Add the Function:BATCH_STOCK_QUOTES

### ISSUE THREAD

**Issue by FreddieSun** [patriques82/alphavantage4j#22]
Could you please add the function :BATCH_STOCK_QUOTES  to obtain the real-time stock information.

**Comment by Danieltreiber** [comment]
I implemented this function in #26

**Comment by patriques82** [comment]
I have updated bintray so all users of the library will be able to use the batch function. It would be great if you also could provide an example in the README, so that users more easily could understand how to use the function. Thanks again @Danieltreiber
