### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by daydream11** [patriques82/alphavantage4j#23]
Could not get unknown property 'bintray_user' for object of type com.jfrog.bintray.gradle.BintrayExtension. Open File

![image](https://user-images.githubusercontent.com/29968593/37385288-72fcee6c-2779-11e8-8153-e5bb3bfa327b.png)

**Comment by patriques82** [comment]
Why are you cloning the project when you can use the gradle installation? Are planning to contribute? The bintray_user is my bintray user name and bintray_key is my password. They are stored local on my computer and not supposed to be exported with the project.
