### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by bugsbyteyou** [patriques82/alphavantage4j#25]
Hi, 

First of all, thank you for this project!

I would like to fork your project, but I'm having trouble building it.

I'm running into the following issue:

`Could not get unknown property 'bintray_user' for object of type com.jfrog.bintray.gradle.BintrayExtension.`

Am I doing something wrong ?

**Comment by RuiBandarra** [comment]
Nevermind, I see its being setup in the build.gradle and is your bintray credentials.

New to bintray and glade.
