### ISSUE TITLE
Proposing to add pom.xml

### ISSUE THREAD

**Issue by markusmaresch** [patriques82/alphavantage4j#27]
Asking to add the attached pom.xml to the root - would make it easier for Maven users ..
Great tool !

[pom.xml.zip](https://github.com/patriques82/alphavantage4j/files/2030141/pom.xml.zip)

**Comment by patriques82** [comment]
Hi @markusmaresch. Thanks for your proposal. I have actually had an pom file before in the repo but many people complained that it did not work, so I removed it. As I am not very familiar with Maven, it would be great if you could provide a complete working pom and I will gladly add it, or better if you like to be a contributor add it by a PR.

**Comment by team172011** [comment]
Very nice code base! pom.xml and publishing to the maven central repository would be pretty nice.

**Comment by jp295m** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.jose</groupId>
  <artifactId>alphavantage4jmvn</artifactId>
  <version>0.0.1</version>
  <build>
  		<sourceDirectory>${pom.basedir}/src/main/java</sourceDirectory>
		<testSourceDirectory>${pom.basedir}/src/test/java</testSourceDirectory>
		<resources>
			<resource>
				<directory>${pom.basedir}/src/main/resources</directory>
				<includes>
					<include>*.dtd</include>
					<include>META-INF/*.xml</include>
					<include>*.properties</include>
				</includes>
			</resource>
			<resource>
				<directory>${pom.basedir}/config</directory>
				<includes>
					<include>*.properties</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
				<executions>
					<execution>
						<id>default-compile</id>
						<phase>compile</phase>
						<goals>
						  <goal>compile</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
 	</build>
  <dependencies>
  		<dependency>
		    <groupId>com.jfrog.bintray.gradle</groupId>
		    <artifactId>gradle-bintray-plugin</artifactId>
		    <version>1.8.0</version>
		</dependency>
		<dependency>
		    <groupId>com.google.code.findbugs</groupId>
		    <artifactId>jsr305</artifactId>
		    <version>3.0.2</version>
		</dependency>
		<dependency>
		    <groupId>javax.annotation</groupId>
		    <artifactId>javax.annotation-api</artifactId>
		    <version>1.3.2</version>
		</dependency>
		<dependency>
		    <groupId>com.google.code.gson</groupId>
		    <artifactId>gson</artifactId>
		    <version>2.8.5</version>
		</dependency>
  </dependencies>
</project>
