### ISSUE TITLE
Technical indicators [macdext, ultosc] not working

### ISSUE THREAD

**Issue by nsdhillon1** [patriques82/alphavantage4j#29]
Due to missing parameter, macdex and ultosc technical indicators result in an error.

**Comment by nsdhillon1** [comment]
[patch.zip](https://github.com/patriques82/alphavantage4j/files/2305168/patch.zip)

**Comment by nsdhillon1** [comment]
Pull request created
https://github.com/patriques82/alphavantage4j/pull/30

**Comment by nsdhillon1** [comment]
Didnt meant to close this issue, not sure how it got closed.

**Comment by patriques82** [comment]
Hi, I have a lot to do this week. But I will look in to it and try to merge your PR as soon as I can. Thanks!

**Comment by nsdhillon1** [comment]
Thanks!

**Comment by patriques82** [comment]
Published your PR:s to version 1.3
