### ISSUE TITLE
Naming of TimeSeries missleading

### ISSUE THREAD

**Issue by team172011** [patriques82/alphavantage4j#36]
I think that the naming of the `TimeSeries ` class is missleading, because it is not a series that stores data, but a kind of `AlphaVantageConnectionManager`. The `Daily `, `IntraDay`, `Monthly`, ..., should be called a `TimeSeries` (maybe with a TimeLevel flag) because they store the corresponding data.
This change would also remove a lot of potential errors by calling the wrong `TimeSeries#intraDay` ,`TimeSeries#daily`, `TimeSeries#weekly` function.

I would suggest to rename `TimeSeries` to something like `AlphaVantageConnectionManager` and for example let the `intraDay` method return a `TimeSeries` object with stock data and a flag (maybe an enum) that describes the time period

**Comment by patriques82** [comment]
I don't think this is necessary. The intention of the class structure is to follow the Alpha Vantage standards used by their rest api and also their documentation.
