### ISSUE TITLE
Package naming improvements

### ISSUE THREAD

**Issue by cbmarc** [patriques82/alphavantage4j#4]
Hello!

I happened to look at your code and I think it would be cool to follow the [Package Naming Conventions](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).

Code itself looks pretty solid but there is even a default package.  

**My proposal**
Start with a `co.alphavantage ` package and elaborate from there. Also underscores are used as some special character for packages that should start with illegal characters, such as reserved words or numbers:

`package int_.mypackage` -> int is a reserved word.
`package com.example._123name` -> 123name is not legal, so we prefix it with an underscore.

**Package structure proposal**
`co.alphavantage`
`co.alphavantage.input`
`co.alphavantage.input.technicalindicator`
`co.alphavantage.input.timeseries`
`co.alphavantage.output`
`co.alphavantage.output.technicalindicator`
`co.alphavantage.output.technicalindicator.data`
`co.alphavantage.output.timeseries`
`co.alphavantage.output.timeseries.data`

I would start with this =)

**Comment by patriques82** [comment]
Go ahead, if you like to do this, that would be great!
