### ISSUE TITLE
ForeignExchange Call

### ISSUE THREAD

**Issue by sholafalana** [patriques82/alphavantage4j#40]
The ForeignExchange class was able to convert value from one currency to another but here is another API call in the documentation that is not working https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=EUR&to_symbol=USD&outputsize=full&apikey=demo . the input in this case is FX_DAILY, EUR, and USD, .

**Comment by patriques82** [comment]
This should be solved now with @ilkerKopanBundle PR, right?

**Comment by ilkerKopanBundle** [comment]
thats right my PR covers that function.
