### ISSUE TITLE
Thought on Finnhub API ?

### ISSUE THREAD

**Issue by alpha332** [patriques82/alphavantage4j#49]
Hi guys,

Just wondering if we can create a new Java wrapper for Finnhub stock API as well : https://finnhub.io/ . They provide 60 free calls/minute with intraday data going back for many years. Websocket streaming is also available for free. I think this is a way better alternative for alpha vantage.

**Comment by ShillSeeker2020** [comment]
Everyone needs to be aware that alpha332 is a shill account for an employee/owner of Finnhub - Spencer Sands

Finnhub has been shill spamming various forums including Reddit, Quora, Github, EliteTrader, Medium and other venues. Their posts have been moderated/deleted in many places.

They have been verified as blatantly copying/redistributing data without license from places include Investors Exchange, Toronto Stock Exchange and Australian Securities Exchange, and have been sent legal cease and desist notices.

They have created multiple shill accounts and even pretend to have user conversations. Their Github repositories are littered with unanswered/unsolved issues.

Other Github projects have refused to deal with this sort of nonsense.

Avoid this one!

Examples of more of their shilling/spam here:
https://github.com/public-apis/public-apis/issues/1137
https://github.com/piquette/finance-go/issues/14
https://github.com/iexg/IEX-API/issues/1410
https://www.reddit.com/r/algotrading/comments/in5u6x/beware_medium_guide_stock_market_apis_for_2020/
