### ISSUE TITLE
Scan query similar to TD Ameritrade

### ISSUE THREAD

**Issue by peterboivin** [patriques82/alphavantage4j#50]
I am trying to develop an app that will act like a stock scanner that will give sma's of a list of stocks.  It does not appear that Alpha Vantage will do this since it only allows 5 requests per min and the premium is 1200 per min per one stock request.  Do you know of any service that will give sma's from a list of stocks? Thank you.

**Comment by patriques82** [comment]
No Im sorry I dont.
