### ISSUE TITLE
Alpha Vantage is an unlicensed vendor

### ISSUE THREAD

**Issue by myxfinance223** [patriques82/alphavantage4j#51]
Hi,

Just want to bring it to you guys' attention that Alpha Vange is distributing market data **illegally** and legal actions have been taken against the company. I suggest you guys to switch to another provider immediately to avoid service disruption. 

Original proof of illegal activity can be found here: https://www.reddit.com/r/algotrading/comments/hnxoy6/beware_alphavantage_is_not_a_licensed_provider/

The following market data has disappeared due to legal actions and more will be coming soon:
+ US real-time data (now they only have end of day data)
+ LSE
+ NSE
+ ASX
+ Torronto stock exchange (TSX)
+ All Nordic exchanges
+ All Baltic exchanges
+ Moscow stock exchange
+ Istanbul stock exchange

I'm just as disappointed as all of you that a great idea was so poorly executed and based on entirely illegal foundation to begin with.

**Comment by patriques82** [comment]
This is still unproven. A screen shot of an email is not considered proof.
