### ISSUE TITLE
Add more technical indicators

### ISSUE THREAD

**Issue by patriques82** [patriques82/alphavantage4j#8]
Currently not all indicators are implemented (far from all). This issue contains the majority of the work remaining. It is quite easy to implement a technical indicator since one can just follow the example of EMA, SMA, etc..

Since I want to finish this project as soon as possible it would be great if collaborators want help out with this. It is a good way to understand the design of the library and maybe make improvements after that. 

The following marked indicators are implemented

- [x] SMA
- [x] EMA
- [x] WMA
- [x] DEMA
- [x] TEMA
- [x] TRIMA
- [x] KAMA
- [x] MAMA
- [x] T3
- [x] MACD
- [x] MACDEXT
- [x] STOCH
- [x] STOCHF
- [x] RSI
- [x] STOCH
- [x] STOCHRSI
- [x] WILLR
- [x] ADX
- [x] ADXR
- [x] APO
- [x] PPO
- [x] MOM
- [x] BOP
- [x] CCI
- [x] CMO
- [x] ROC
- [x] ROCR
- [x] AROON
- [x] AROONOSC
- [x] MFI
- [x] TRIX
- [x] ULTOSC
- [x] DX
- [x] MINUS_DI
- [x] PLUS_DI
- [x] MINUS_DM
- [x] PLUS_DM
- [x] BBANDS
- [x] MIDPOINT
- [x] MIDPRICE
- [x] SAR
- [x] TRANGE
- [x] ATR
- [x] NATR
- [x] AD
- [x] ADOSC
- [x] OBV
- [x] HT_TRENDMODE
- [x] HT_DCPERIOD
- [x] HT_DCPHASE
- [x] HT_PHASOR

**Comment by jessemazzie** [comment]
#12 Pull request for MACD created.
